const cartActions = {
  CART_DROPDOWN_TOGGLE: 'CART_DROPDOWN_TOGGLE',
  ADD_ITEM: 'ADD_ITEM',
  REMOVER_ITEM_FROM_CART: 'REMOVER_ITEM_FROM_CART',
  INCREASE_ITEM: 'INCREASE_ITEM',
  DECREASE_ITEM: 'DECREASE_ITEM'
}

export default cartActions;